apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: webapplicationfirewallwebacls.metacontroller.glueops.dev
spec:
  group: metacontroller.glueops.dev
  names:
    kind: WebApplicationFirewallWebACL
    plural: webapplicationfirewallwebacls
    singular: webapplicationfirewallwebacl
    shortNames:
    - webacl
    - webacls
    - wafwebacl
    - wafwebacls
  scope: Namespaced
  versions:
  - name: v1alpha1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          status:
            type: object
            x-kubernetes-preserve-unknown-fields: true
          spec:
            type: object
            properties:
              web_acl_definition:
                type: string
                description: "Raw JSON string representation of the full AWS WAF WebACL definition"
    subresources:
      status: {}
